theme: jekyll-theme-hacker

linkedin_title: "👋 Welcome to my Data Analysis Portfolio! I’m Emmanuel Nti, a Senior Data Analyst passionate about solving business problems through data. This portfolio showcases projects from my data analysis training, highlighting experimentation, customer behavior, and growth analytics with actionable insights."
